name: Deploy Coronation CMS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.PROD_SERVER_HOST }}
          username: ${{ vars.PROD_SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            echo "Entering project..."
            cd /var/www/production/Coronation-CMS

            echo "Maintenance mode..."
            php artisan down || true

            echo "Syncing code..."
            git fetch origin
            git reset --hard origin/main
            git clean -fd

            echo "Installing dependencies..."
            composer install --no-dev --optimize-autoloader

            echo "Running migrations..."
            php artisan migrate --force

            echo "Clearing caches..."
            php artisan optimize:clear

            echo "Rebuilding caches..."
            php artisan config:cache
            php artisan route:cache

            echo "Fixing permissions..."
            chown -R www-data:www-data storage bootstrap/cache
            chmod -R 775 storage bootstrap/cache

            echo "Restart queues..."
            php artisan queue:restart || true

            echo "App live..."
            php artisan up

            echo "Reloading Nginx..."
            sudo systemctl reload nginx